
target 'GTSpec_Example' do
#  pod 'GTSpec', :path => '../'
pod 'KVOController'
pod 'BlocksKit'
pod 'Masonry'
pod 'AFNetworking',      '~> 2.0'
pod 'SDWebImage',        '~> 3.7.3'
pod 'Objective-LevelDB'
pod 'AutoCoding'
  target 'GTSpec_Tests' do
    inherit! :search_paths
    
  end
end
